server:
  port: 9000
spring:
  application:
    #指定服务名称
    name: zuul
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    system-manager: /system_manager/**
    static-resource: /static_resource/**
    apply-server: /apply_server/**
  servlet-path: /
  ignored-services: '*'
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
jwt:
  config:
    key: swpu
    ttl: 3600000