server:
  port: 9001
spring:
  application:
    #指定服务名称
    name: apply-server
    #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#开启驼峰命名转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true


